Explicitly turn on assemblies for our demo instance
liquidvotingio/liquid-decidim-demo pull request #22
Opened 2021-05-19 10:55 UTC by davefrey

The `decidim-assemblies` gem was already a dependency in the Gemfile.lock, unsure adding it to the Gemfile changes anything but it does make it explicit, and explicitly the Decidim version we want.

2021-05-19 14:23 UTC, oliverbarnes requested changes
Thanks, this made me dig a little to find out what exactly the decidim gem installs, and it looks like both assemblies and proposals are included. Here's an example Gemfile lock for the Sabadell instance (done by Codegram): https://github.com/AjuntamentDeSabadell/decidim-sabadell/blob/master/Gemfile.lock#L129-L148

And their Gemfile only declare decidim itself: https://github.com/AjuntamentDeSabadell/decidim-sabadell/blob/master/Gemfile#L7

I agree we should be explicit about which parts of decidim we're integrating with, but it's better to do it in docs. As for the version, all the dependencies are semantically versioned and follow decidim's own version.

So instead of adding the assemblies gem, how about we actually remove the proposals gem from here, and leave only the decidim and liquidvoting gems?

2021-05-19 14:55 UTC, davefrey commented
I agree, thanks for chasing that up, will push change in moment. Finally I think I like that approach, all the usual Decidim things are in by default, and we LV are clearly an opt-in extension.

2021-05-19 15:47 UTC, davefrey commented
And this reminds me that all those dependencies are included in the lock file because `gem "decidim"` in the `Gemfile` loads all the dependencies in the `decidim.gemspec` file.

2021-05-21 18:47 UTC, oliverbarnes approved these changes

2021-05-21 18:48 UTC, merged